### ISSUE TITLE
Crashlytics detect crashes in Taplytics SDK

### ISSUE THREAD

**Issue by olivierg13** [taplytics/Taplytics-Android-SDK#4]
Hello,

We are using Taplytics and Crashlytics in our app.
Crashlytics is giving us a stacktrace (currently 7 crashes in 2 weeks) that refers to Taplytics SDK.

Unfortunately, as the SDK seems to be obfuscated, the stacktrace is hard to recompose (I paste it at the end of this message).

One solution is to add this line to proguard when compiling your sdk
```
-keepattributes SourceFile,LineNumberTable
```
(source: http://support.crashlytics.com/knowledgebase/articles/202143-eclipse-with-proguard)
Maybe that is already what you do, in this case Crashlytics fails to recompose the trace from a library...

Here is the trace, if that can help you: (thank you very much in advance)

```
java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.taplytics.sdk.analytics.buffalo.cockroach(SourceFile:415)
       at com.taplytics.sdk.analytics.albatross.run(SourceFile:93)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5487)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

thread
       at java.lang.String._getChars(String.java:909)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:147)
       at java.lang.StringBuilder.append(StringBuilder.java:216)
       at org.json.JSONStringer.value(JSONStringer.java:249)
       at org.json.JSONObject.writeTo(JSONObject.java:672)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONObject.writeTo(JSONObject.java:672)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:602)
       at org.json.JSONArray.toString(JSONArray.java:574)
       at com.taplytics.sdk.donkey.stingray(SourceFile:343)
       at com.taplytics.sdk.donkey.buffalo(SourceFile:320)
       at com.taplytics.sdk.donkey.doInBackground(SourceFile:299)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

thread
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:579)
       at java.lang.Thread.getAllStackTraces(Thread.java:521)
       at com.crashlytics.android.v.a(SourceFile:1419)
       at com.crashlytics.android.v.a(SourceFile:66)
       at com.crashlytics.android.N.call(SourceFile:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.crashlytics.android.internal.am.a(SourceFile:44)
       at com.crashlytics.android.internal.aa.run(SourceFile:13)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by MattyKuzyk** [comment]
Hey @olivierg13, what version of the Taplytics SDK were you seeing this in?

**Comment by olivierg13** [comment]
Hello @MattyKuzyk 

Our app in version 1.7.0 was out 2-3 weeks ago, so I suppose I was using 1.3.20.

It is true that we did not see this bug anymore on our 1.8.0 app, that was released Monday with probably 1.3.21 or 1.3.22. Did you fix it? I am going to stop importing the SDK with 'com.taplytics.sdk:taplytics:+@aar' but the current version explicitly.

Cheers,

Olivier

**Comment by MattyKuzyk** [comment]
Not fixed yet, looking into it. Knowing what version this stack trace appeared on just helps us debug it is all.

**Comment by olivierg13** [comment]
Sure, don't hesitate if you need something.

**Comment by VicV** [comment]
Hey @olivierg13 I put some extra safety around this area in our code. 

The SDK you were seeing this on was 1.3.18 or 1.3.19 (stacktrace matches up to both of those).

Upgrade to the newest SDK, 1.3.24 and these problems shouldn't exist anymore.

Thanks for the help!

**Comment by olivierg13** [comment]
@VicV Thanks, I'll update with the new version soon.

Cheers,

Olivier
